[package]
name = "rdlink-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "client"
path = "src/main.rs"

[dependencies]
rdlink-proto = { path = "../proto" }
ffmpeg-the-third = "6"
image = { version = "0.25", default-features = false, features = ["png"] }
winit = "0.30.13"
wgpu = "30.0.1"
pollster = "1.0.1"
# T6/T8 将加入: winit, wgpu, rdlink-transport
